== 4.1.0

=== Métriques des plugins Kafka


[.notes]
--
* KIP-877
--

=== Qu'est-ce qu'un plugin Kafka ?

[.step]
* *Producer*: Serializer, Partitioner, ProducerInterceptor
* *Consumer*: Deserializer, ConsumerInterceptor
* *Connect*: Converter, Transform, Predicate, Connector, Task
* *Broker*: Authorizer, CreateTopicPolicy, ClientQuotaCallback, ReplicaSelector

[.notes]
--
* problème : *pas de standard*, duplication de metriques, difficulté à associer métriques plugin/client
--

=== Implémentation

[.large-code-exemple]
--


[source,java,highlight=1..2|6..13|15..19]
----
public class MyInterceptor<K, V> 
  implements ProducerInterceptor<K, V>, Monitorable {
  
  private Sensor sensor;

  @Override
  public void withPluginMetrics(PluginMetrics metrics) {
    sensor = metrics.sensor("onSend");
    MetricName rate  = metrics.metricName("rate",  "Average number of calls per second.", new LinkedHashMap<>());
    MetricName total = metrics.metricName("total", "Total number of calls.",             new LinkedHashMap<>());
    sensor.add(rate,  new Rate());
    sensor.add(total, new CumulativeCount());
  }

  @Override
  public ProducerRecord<K,V> onSend(ProducerRecord<K,V> record) {
    sensor.record();
    return record;
  }
}
----

--

[.notes]
--
* deux nouvelles interfaces : Monitorable et PluginMetrics
* facilité : métriques attachées au Metrics du composant hôte, taguées automatiquement pour identifier le plugin.
* plus besoin de gérer les reporters : c'est fait automatiquement.
--

=== OAuth2 grant type

[.step.without-bullets]
* ❗️ *Problème*: seul client_credentials supporté
** Secret statique = Potentiel risque de sécurité
[.step.without-bullets]
* 🔐 *Solution*: jwt-bearer (RFC 7523)
** Authentification via JWT signé

[.notes]
--
* Beaucoup d'IdP (cloud) n'*autorisent pas* client_credentials (secret statique)
* Sécurité + flexibilité (RBAC, multi-tenant)
* KIP-1139
--


=== Kafka Connect: support plugins multi-versions

[.step]
* *Problème*: 1 version par cluster
* Difficulté à gérer les montées de versions, rollback etc ...
* 🎛️ *Nouveauté*: Support de plusieurs versions de plugins sur un cluster 

[.notes]
--
* plugin type connecteur postgresql, debezium, etc.
* Upgrades en 2 temps avec rollback facile
* Réduction clusters Connect
* KIP-891 - 4.1.0
--

=== Installation

[source,bash,highlight=1..10|6..8]
----
opt/
  plugins/
    foo-connector-1.8/
      foo-connector-1.8.jar
      foo-dependencies-1.0.jar
    foo-connector-1.9/
      foo-connector-1.9.jar
      foo-dependencies-1.1.jar
    bar-connector/
      bar-connector-1.0.jar
----


=== Utilisation

[.step]
* Spécifier la version souhaitée
** `"xxx.plugin.version": "[3.5,)"`
* Versions visibles de manière distincte dans l'API

[.notes]
--
* notation maven range
* API mise à jour
--
